### ISSUE TITLE
I can't seem to get the "right" pallete

### ISSUE THREAD

**Issue by Pomax** [leeoniya/RgbQuant.js#12]
I'm running rgbquant on the following image in order to get the 10 most dominant colours out:

![screenshot 68](https://cloud.githubusercontent.com/assets/177243/6093576/801be58a-aeb9-11e4-99e0-85e7da0f53da.png)

but instead most of the settings I've tried seem to come up with the following quantization:

![screenshot 69](https://cloud.githubusercontent.com/assets/177243/6093583/c070b0f2-aeb9-11e4-855f-8b3638e5a029.png)

Are there specific settings that work best for quantizing such that the final palette is closest to the original image?

(the orange is obvious, but also the little yellow bit in the original image has become pink in the quantized result, and the tiny plushy at the bottom has become half pink, too =)

**Comment by leeoniya** [comment]
try setting `minHueCols` to something big. 4096+.

**Comment by Pomax** [comment]
still the same. With the following, the result is still pretty much the same color rewriting:
```
    var opts = {
      colors: 10, // also tried 20, still roughly the same but too many colours
      boxSize: [64, 64], // also tried 16,16 and 200,200
      initColors: 4096, // started at 256
      minHueCols: 4096
    };
```

if github does animated gif, here's the new result:

![fox](https://cloud.githubusercontent.com/assets/177243/6093603/e1db064c-aeba-11e4-8f3b-40364ac45c83.gif)

**Comment by leeoniya** [comment]
so for some odd reason - and i've noticed this before - chrome and ff always give slightly different results. i'm not sure if this has to do with some bug in the histogram sorting or something else. it happens to be quite noticeable in this case, where the total pixel count is low enough for the smoothness of histogram statistics to break down. 

chrome:
![chrome](https://cloud.githubusercontent.com/assets/43234/6093658/e4139790-aecd-11e4-9e37-012e69f1a29d.png)

firefox:
![firefox](https://cloud.githubusercontent.com/assets/43234/6093657/e4130cda-aecd-11e4-877c-042d9812673f.png)

**Comment by leeoniya** [comment]
sorry, i missed the full image. one sec.

**Comment by Pomax** [comment]
hm, looks like FF gets the "foxes" right, but the cheese wrong, with Chrome doing the opposite. That's quite weird! Would rgbquant still work if it didn't have a canvas to work with, but simply ran on top of a uint8array? The jpg.js library I'm using decodes jpg independently of what the browser/canvas will do, turning the data into an int array with the "correct" values (at least, as far as photoshop shows me), so if rgbquant relies on the canvas for certain operations that might be one possible reason there's color oddities showing up (thinking out loud)

**Comment by leeoniya** [comment]
i'll have to investigate, lots of stuff is tending to favor quantizing to pink. there's no specific reason i can think of for this to be happening. i tried using `colorDist: "manhattan"` rather than `colorDist: "euclidean"`, but no difference. it seems to be picking the right palette, but something in the reduction step (the color distance) is being inaccurate. which is weird cause the same colorDist func is used for the palette reduction step.

the lib doenst need canvas *at all*, you can pass it a Uint8Array + width.

**Comment by Pomax** [comment]
Comparison shot between irfanview, jpg.js-loaded-onto-canvas, and what Firefox turns the image into if it's loaded as `<img>` instead of on a canvas (note the `<img>` is pretty wrong wrt the other two), so this might also be caused by weird things happening by tapping into the image's data (say if it's getting used to paint onto a canvas for analysis)

![screenshot 70](https://cloud.githubusercontent.com/assets/177243/6093698/22626062-aebf-11e4-883e-318ec6d442a9.png)

**Comment by leeoniya** [comment]
the way they all display the jpegs may be slightly different from color profiles etc, but i wouldnt expect jpeg decoders to be wrong wrt the raw `ImageData`, it should be identical. though i have seen some foo with the first gradient png in the demo on different machines/browsers.

let me know how it goes, i'm not getting my hopes up, though,

**Comment by leeoniya** [comment]
i have a question: how real is this issue for your use-case? it looks like in both cases, the resulting palette is pretty good, despite the reduction pass not quantizing as expected.

as should be apparent, when you get down to really low color counts (<16), the answers become less black-and-white (pardon the pun) in terms of right or wrong. So there is no single "correct" palette of 5 colors for a gradient of 10k that fall all over the hue/saturation/luminance space.

i consider the generated palettes to be quite good, with no additional amount of tweaking that will yield non-subjective results.

just to clarify,  i'm not intending to close the issue, regardless of answer. the reduction pass should probably do a better job.

**Comment by Pomax** [comment]
pretty real - it's about matching colours in images to one or more fountain pen inks commercially available, so even in this example the "colour of the fox" should come out looking reasonably the same, since it makes up a fairly large part of the image, Instead it becomes a colour that's visibly off.

http://mighty-lake-2303.herokuapp.co => "match layout" from the selector in the upper left, then drag and drop an image onto the drop zone. This runs the image through rgbquant and does (Lab 'L' based) color matching to find the closest available inks that are commercially available. Ideally, this would give the situation where one can write something using a particular ink, save that as jpg, and then dropping that onto the matches, so that one of the best matches is simply the ink that was used to do the writing with (barring colors messing up during the 'taking a picure' stage of course)

**Comment by leeoniya** [comment]
i'll be fairly busy for a week or two, but if you find a more accurate way to color match (that has an acceptable perf profile), i'd be interested in what you find and maybe implement it in RgbQuant

**Comment by Pomax** [comment]
will keep you posted

**Comment by leeoniya** [comment]
@Pomax relevant discussion (though some of it in Russian): https://github.com/igor-bezkrovny/image-quantization/issues/4

**Comment by Pomax** [comment]
that is certainly an interesting discussion, thanks for letting me know!
