### ISSUE TITLE
when using array input as data, is there a way to indicate byte layout?

### ISSUE THREAD

**Issue by Pomax** [leeoniya/RgbQuant.js#13]
For instance, I have a JPEG array that has layout [r,g,b,r,g,b,etc] rather than [r,g,b,a,r,g,b,a,etc] and it seems to be throwing rgbquant off quite a bit. Is there a way to tell it which channels live on which indices?

**Comment by leeoniya** [comment]
there's no way to do this and i'm not sure if the extra code to account for varying layouts in every function & bitshift is worth it - it would bloat the code for sure and likely impact perf quite a bit for all use-cases. your best bet is to just do the alpha insertion ahead of time.

**Comment by Pomax** [comment]
fair enough
