### ISSUE TITLE
Emit "progress" events to notify users in a web app use-case

### ISSUE THREAD

**Issue by JohnRandom** [leeoniya/RgbQuant.js#14]
I'm using RgbQuant on a website, to extract brand colours from an image provided by a user. The algorithm is quite fast, but it can still take a while for huge images, and we all know users are weird creatures. In order to tell a user that the process is still running and didn't hang, I'd like to have an event that is emitted frequently, that could look like:
```
q.on('progress', function(progress) {
  // ...
});
```

**Comment by leeoniya** [comment]
There's no meaningful way to measure 'progress', there are different stages, but they're very uneven and won't mean much. If you're looking for a heartbeat and not freeze the UI, the most straightforward solution would be to run RgbQuant in a Web Worker and use setInterval in the main UI thread to serve as a heartbeat until the worker responds with the result. This will keep everything smooth, uniform and simple.

You can do the same thing without webworkers if you're ok with the UI freezing:

```js
var it = window.setInterval(function() {
    console.log('still working...');
}, 1000);

var pal = q.sample(image);

window.clearInterval(it);

alert('done!');
```

If you don't need absolute pixel-perfect images, something you may consider doing is quickly scaling down large images via Canvas before feeding them to RgbQuant.

**Comment by leeoniya** [comment]
closing for now, feel free to re-open if needed.
