### ISSUE TITLE
set color

### ISSUE THREAD

**Issue by subrat71** [leeoniya/RgbQuant.js#16]
Hi,
I just go through your library and its really great stuff. And it reduce the image perfectly. But is there any way i can change the color. 
Suppose i give option.color = 4; 
and after update click i need to show 4 color pallets and by clicking on them i want to change that color on image.
is it possible ??

**Comment by leeoniya** [comment]
I don't understand what you mean. Can you provide an example image, the generated palette and describe what you want to happen to the original image or even use Paint or Photoshop to illustrate the result?

**Comment by subrat71** [comment]
just go through this url http://www.demo.inksoft.com/demo/DesignStudio/Home#/artLocations
- select blank canvas
- upload image - from computer
- select logo or multi-color (first option)
- choose 4 colors and click on continue then wait for image processing.
- then choose a color from select color option.

i need that feature on image. Is that possible.

**Comment by leeoniya** [comment]
i see. there is no feature for this because it is very easy to do yourself with a simple loop after reducing the image.

1. first reduce the image to the desired quantity using RgbQuant.
2. loop through the resulting pixels and replace the source color with the target color.

however, i would recommend for this specific case to start with a fixed palette of available inks and let RgbQuant to select the most appropriate ink colors automatically. this could eliminate the ink selection step entirely unless you want to still give the customer the option to use completely different, non-matching inks:

```js
var opts = {
    colors: 6,
    palette: [
        [192,36,128],      // ink 1
        [66,200,19],       // ink 2
        [75,173,100]       // ink 3
        // etc...
    ],
    reIndex: true,
    useCache: false
};

var q = new RgbQuant(opts);
q.sample(img);
var pal = q.palette();
var outA = q.reduce(img);
```

**Comment by subrat71** [comment]
Thank you for helping me.

On 21 May 2015 at 12:00, Leon Sorokin <notifications@github.com> wrote:

> i see. there is no feature for this because it is very easy to do yourself
> with a simple loop after reducing the image.
>
>    1. first reduce the image to the desired quantity using RgbQuant.
>    2. loop through the resulting pixels and replace the source color with
>    the target color.
>
> however, i would recommend for this specific case to start with a fixed
> palette of available inks and let RgbQuant to select the most appropriate
> ink colors automatically. this could eliminate the ink selection step
> entirely unless you want to still give the customer the option to use
> completely different, non-matching inks:
>
> var opts = {
>     colors: 6,
>     palette: [
>         [192,36,128],      // ink 1
>         [66,200,19],       // ink 2
>         [75,173,100]       // ink 3
>         // etc...
>     ],
>     reIndex: true,
>     useCache: false
> };
> var q = new RgbQuant(opts);
> q.sample(img);var pal = q.palette();var outA = q.reduce(img);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leeoniya/RgbQuant.js/issues/16#issuecomment-104152975>
> .
>



-- 
Thanks and Regards
SUBRAT KUMAR SARANGI
subrats@riaxe.com
7504805045

**Comment by leeoniya** [comment]
something like

```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Test Reduce</title>
	<script src="rgbquant.js"></script>
</head>
<body>
	<img id="test_img" src="confused.jpg">
	<script>
		var opts = {
			colors: 10,
			palette: [
				[0, 0, 0],
				[0, 3, 82],
				[0, 51, 0],
				[0, 163, 103],
				[4, 140, 0],
				[14, 44, 240],
				[23, 108, 255],
				[51, 204, 51],
				[64, 179, 255],
				[68, 72, 74],
				[71, 20, 5],
				[79, 0, 0],
				[83, 117, 45],
				[100, 27, 209],
				[112, 79, 1],
				[153, 0, 0],
				[153, 102, 51],
				[163, 130, 4],
				[167, 255, 153],
				[168, 168, 168],
				[171, 141, 108],
				[178, 23, 255],
				[185, 219, 151],
				[204, 102, 0],
				[204, 204, 105],
				[219, 202, 156],
				[227, 227, 227],
				[240, 0, 0],
				[247, 255, 135],
				[255, 51, 228],
				[255, 102, 0],
				[255, 173, 239],
				[255, 215, 18],
				[255, 243, 227],
				[255, 255, 0],
				[255, 255, 255],
			],
			reIndex: true,
			useCache: false
		};

		var q = new RgbQuant(opts);

		window.setTimeout(function() {
			var img = document.getElementById("test_img");
			q.sample(img);
			var pal = q.palette();
			var outA = q.reduce(img);

			var can = document.createElement("canvas"),
				ctx = can.getContext("2d");

			can.width = img.naturalWidth;
			can.height = img.naturalHeight;

			var imgd = ctx.getImageData(0,0,can.width, can.height);

			imgd.data.set(outA);

			ctx.putImageData(imgd, 0, 0);

			document.body.appendChild(can);
		}, 250);
	</script>
</body>
</html>
```
