### ISSUE TITLE
NPM package contains additional "working" files not present in repo

### ISSUE THREAD

**Issue by darosh** [leeoniya/RgbQuant.js#18]
Here is the list of additional files and folders I got in ```node_modules/rgbquant``` after ```npm i rgbquant```
* _bak\
* dither\
* palettessrc\
* src\convert.js
* src\diff.js
* src\rgbquant_2.js
* src\rgbquant_3.js
* webgl.txt
* dither.txt

**Comment by leeoniya** [comment]
interesting, looks like gitignore or npmignore needs a poking. thanks!

**Comment by darosh** [comment]
@leeoniya you're welcome, thanks for this inspiring work, I'm experimenting with similar stuff: https://github.com/darosh/colorgram-js

**Comment by leeoniya** [comment]
fixed
