### ISSUE TITLE
Error: Uncaught Nothing has been sampled, palette cannot be built

### ISSUE THREAD

**Issue by generalov** [leeoniya/RgbQuant.js#2]
Given I draw to the canvas an image 1x3 pixels with blue, green and red dots
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAADCAIAAADdv/LVAAAADUlEQVQI12NgYPgPQwAR+gL+H61IqAAAAABJRU5ErkJggg==

when I try to get a palette:

```
var q = new RgbQuant({colors: 3}),
      paletteArray;
q.sample(canvas);
paletteArray = q.palette();
```

then I see an exception:

```
Error: Uncaught Nothing has been sampled, palette cannot be built.
```

Why? Is there any limitations for images?

**Comment by ein-langer-weg** [comment]
I have the same problem with the following image (a white image with one color):
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAAJYCAYAAACadoJwAAAACXBIWXMAAAsTAAALEwEAmpwYAAAHXElEQVR4nO3BMQEAAADCoPVPbQZ/oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+A1ALAAFujETzAAAAAElFTkSuQmCC
how should the options be to become an array with one color in this case?

**Comment by leeoniya** [comment]
This image is fully transparent `rgba(0,0,0,0)` so there's no "color" in it.

Also, RgbQuant does not support alpha-transparency and has code that specifically excludes `alpha == 0` pixels [1]. Perhaps a warning can be added to the console in such cases and/or an empty array can be returned.

[1] https://github.com/leeoniya/RgbQuant.js/blob/master/src/rgbquant.js#L612

**Comment by ein-langer-weg** [comment]
Okay great, Thanks a lot @leeoniya (:
