### ISSUE TITLE
Question: how do I use this library to save the quantized image as a file?

### ISSUE THREAD

**Issue by bshyong** [leeoniya/RgbQuant.js#21]
I'm trying to use this library with AWS Lambda to return the quantized image as a response.

**Comment by leeoniya** [comment]
not familiar with the specifics of Lambda, but if you're using nodejs in it, look at the example in the readme [1]. `.reduce()` will return an  array of subpixels and you can use any png (or other image format) encoding lib on npm to turn it into an image to output alongside an appropriate Content-Type header.

[1] https://github.com/leeoniya/RgbQuant.js#nodejs

**Comment by leeoniya** [comment]
closing, since rgbquant doesn't handle image encoding, which should be delegated to other libs.
