### ISSUE TITLE
Demo site has 404 error

### ISSUE THREAD

**Issue by AlfredJKwack** [leeoniya/RgbQuant.js#22]

**Comment by leeoniya** [comment]
@AlfredJKwack

Ah yes, i re-deployed the server recently. thanks for the heads up. i'll poke it this evening..

The demo was just a copy of `/demo`. I've pushed it to a `gh-pages` branch.

http://leeoniya.github.io/RgbQuant.js/demo/

**Comment by leeoniya** [comment]
BTW, i'd also recommend you check out https://github.com/igor-bezkrovny/image-quantization

Igor and I had a lot of back-and-forth over email a while back. He started with RgbQuant and added alpha support, converted to TypeScript, fixed some minor dithering bugs, followed by implementing the awesome WuQuant v2 and Riemersma (Hilbert Curve) dithering. His lib's terminology is a bit strange, but it's hard to argue with results :)

If speed is no object, Wu v2 & Riemersma dithering give absolutely phenomenal results in every single test case with 0 tweaking. If you need speed and tweakable options, then RgbQuant may work out better.

**Comment by AlfredJKwack** [comment]
Thanks for the tips. I'll look into those.

**Comment by leeoniya** [comment]
relinked in readme
