### ISSUE TITLE
Rebuilding the palette

### ISSUE THREAD

**Issue by jonneva** [leeoniya/RgbQuant.js#25]
I am using rgbquant.js on a page where I upload images and reduce amount of colours. It works great. 

However, I don't understand the palette locking & regeneration. How do I programmatically clear & rebuild the palette from javascript when a new picture has been uploaded? I don't see a function that clears the palLocked flag. What was the intention of the authors in this regard?

**Comment by leeoniya** [comment]
once the palette is generated it is done.

the purpose of feeding multiple images prior to palette generation is to create a single palette that would work well to quantize a variety of images. this is most useful for multiple frames of a single gif animation, where you can have a single global palette and all images must map to a color in it. GIF allows you to also have a palette per frame but this results in huge files.

if you're simply quantizing an image at a time, then you need to create a new RgbQuant instance for every image.

hope that helps.

**Comment by leeoniya** [comment]
plz reopen if still an issue.
