### ISSUE TITLE
Visual artifacts

### ISSUE THREAD

**Issue by dirceupj** [leeoniya/RgbQuant.js#26]
I'm trying to apply RgbQuant.js's quantization on a canvas where I've draw some PNGs (tiles from a mapping application).

These PNGs have some holes (transparency).

Also they not fill the canvas, leading to lots of "white pixels".
<img width="903" alt="captura de tela 2018-02-23 as 18 38 15" src="https://user-images.githubusercontent.com/20571/36618380-b7c63de6-18c9-11e8-8274-33dbddacc678.png">
Left is the canvas before quantization. Right is after quantization.

After `q.reduce(canvas)` I'm using `drawPixels` function I found on RgbQuant.js's demo to render a canvas with quantization result.

But I'm getting lots of artifacts on the most dark pixels.

Tried with: `method: 1` and `method: 2`, `initColors: 8128` or with default initColors...
Using options: `colors: 32,
minHueCols: 0`

Would you/someone have any idea how to getting it to work properly?

**Comment by leeoniya** [comment]
hey @dirceupj 

rgbquant does not support alpha transparency. i actually don't understand why it would be needed for satellite images (as opposed to map layers like roads, places, etc.). the easiest solution would be to flatten the images before quantization. i'm pretty sure you can do this just with Canvas and drawImage & composite ops.

you can also take a look at a project derived from rgbquant [1] that supports alpha.

[1] https://github.com/ibezkrovnyi/image-quantization

**Comment by dirceupj** [comment]
Thank you for instant reply.

In fact it is a map layer derived from drone imaging. The images are "glued" and I expect transparency outside its boundaries and some holes. But it seems other pixels are also with transparency.

I'm first drawling them into the canvas and then loading into RgbQuant.js. I supposed that canvas didn't have transparency and flattens when I `.drawImage()` on it. But I may have supposed that wrong.

Thanks for pointing to @ibezkrovnyi/image-quantization, I've tried it and works as expected and it is based on your great work here.
