### ISSUE TITLE
RgbQuant.js as a node.js module

### ISSUE THREAD

**Issue by frankred** [leeoniya/RgbQuant.js#6]
First, I <3 RgbQuant, I use it for analysing web page screenshots.

Have you ever thought about making this as a node.js module, where you can overgive a path to the image on the filesystem. This would be pretty awesome...

Best Regards,
Frank

**Comment by forresto** [comment]
I wanted to use on node. We're already using Automattic/node-canvas, and only put those Canvas objects into `q.sample()`. I only had to a case to detect those canvases: https://github.com/forresto/RgbQuant.js/commit/1106472d52cc44f8a615c3b05a31cabeeafd9a27 and do the `module.exports`. Feel free to use 

```
  "dependencies": {
    "rgbquant": "git://github.com/forresto/RgbQuant.js.git#master",
    ...
```

if that's helpful for you.

**Comment by leeoniya** [comment]
hey @forresto,

i do take pull requests :)

**Comment by forresto** [comment]
I was afraid that I only fixed it for my narrow use case... loading images etc. would be more work.

**Comment by leeoniya** [comment]
imo, your changes have enough LOC:#win ratio to make some useful headway on this request. it's still not "batteries included" but i dont think this lib will ever get there cause of the aforementioned hard-deps issue.

**Comment by forresto** [comment]
now
```
  "dependencies": {
    "rgbquant": "git://github.com/leeoniya/RgbQuant.js.git#master",
    ...
```

**Comment by Pomax** [comment]
very interested in being able to pull this down via npm, even if it needs something feed it pixel data! I'd be 100% already with only getting `require("rgbquant")` and then still needing my own code for getting pixeldata in there.

(Used it on inkcyclopedia.org, but I'm playing around with some more things and want to start using it on http://mighty-lake-2303.herokuapp.com =)

**Comment by leeoniya** [comment]
https://www.npmjs.com/package/rgbquant

yay?

**Comment by Pomax** [comment]
101% yay!

There is no "suggest" as such - most of the time installing dependencies that never get used because you never touch the codepath that has the `require` call is considered just fine, since you can tell things like browserify to simply ignore libraries that won't be needed in the browser anyway. 

You can add node-canvas as a dependency, and then in the code itself make sure to use something like:
```
var canvas;
if(typeof process !== "undefined" && process.argv) {
  // we're in node, use plain require
  canvas = require("node-canvas");
} else {
  // we're not in node, assume we're in the browser
  canvas = document.createElement("canvas");
}
...
```
so that the right thing gets picked in the right context. For those then doing bundling for the browser using browserify etc. we can simply say "turn `require("node-canvas")` into `"";` and move on", knowing that as a bundle for browsers, that's a harmless substitution.

**Comment by frankred** [comment]
Nice!

Just playing arround with canvas and rgb_quant but did not get a working code example:

```js

var RgbQuant = require('rgbquant');
var Canvas = require('canvas')
var Image = Canvas.Image;
var rgb_quant = new RgbQuant({colors: 4, method: 2, initColors: 4096, minHueCols: 0});
var canvas = new Canvas(200, 200);
var ctx = canvas.getContext('2d');

fs.readFile('./screenshots/test.png', function (err, data) {
    if (err) {
        throw err;
    }
    img = new Image;
    img.src = data;

    ctx.drawImage(img, 0, 0, img.width, img.height);

    rgb_quant.sample(img);
    rgb_quant.palette(true);
});

```


Getting this error, even if I change ``` rgb_quant.sample(img);``` to ``` rgb_quant.sample(ctx);``` :

```
C:\workspace-js\>node sandbox.js
C:\workspace-js\node_modules\rgbquant\src\rgbquant.js:536
                        boxes = makeBoxes(width, buf32.length / width, boxW, boxH),
                                                      ^
TypeError: Cannot read property 'length' of undefined
    at RgbQuant.colorStats2D (C:\workspace-js\content-crawler-suppilo-nodejs\node_modules\rgbquant\src\rgbquant.js:536:34)
    at RgbQuant.sample (C:\workspace-js\content-crawler-suppilo-nodejs\node_modules\rgbquant\src\rgbquant.js:93:17)
    at C:\workspace-js\content-crawler-suppilo-nodejs\sandbox.js:20:15
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by frankred** [comment]
Got it! This is working, maybe other people are interested how to combine **rgb quant** and **node-canvas**:

```js
var fs = require('fs');

var RgbQuant = require('rgbquant');
var rgb_quant = new RgbQuant({colors: 4, method: 2, initColors: 4096, minHueCols: 0});

var Canvas = require('canvas')
var Image = Canvas.Image;
var canvas = new Canvas(200, 200);
var ctx = canvas.getContext('2d');

fs.readFile('./screenshots/test.png', function (err, data) {
    if (err) {
        throw err;
    }
    img = new Image;
    img.src = data;

    ctx.drawImage(img, 0, 0, img.width, img.height);

    rgb_quant.sample(canvas);
    rgb_quant.palette(true);
});

```

**Comment by Pomax** [comment]
might we worth creating as example for pointing to from the readme on github?

**Comment by leeoniya** [comment]
not opposed, though i'd prefer it reformatted as below (untested). i'll add it to the readme if someone tests it and gives the thumbs up.

```js
var fs = require('fs'),
	Canvas = require('canvas'),
	Image = Canvas.Image,
	RgbQuant = require('rgbquant');

var imgPath = "./test.png",
	img, can, ctx, q, pal, out;
	
fs.readFile(imgPath, function(err, data) {
	img = new Image;
	img.src = data;

	can = new Canvas(img.width, img.height);
	ctx = can.getContext('2d');
	ctx.drawImage(img, 0, 0, img.width, img.height);

	q = new RgbQuant();
	q.sample(can);
	pal = q.palette(true);
	out = q.reduce(can);
});
```

**Comment by frankred** [comment]
Just testet your code snippet. It works!
